import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { promisify } from 'node:util';
import { execFile } from 'node:child_process';
import { parsePipeline, type ForgeArtifactRecord, type ForgeJobRecord, type ForgePipelineDefinition, type ForgeRunStatus, type ForgeStepDefinition, type ForgeStepResult } from './core.ts';
import { checkoutExactSha } from './git.ts';
import { FilesystemArtifactStore } from './artifacts.ts';
const inheritedKeys = ['PATH', 'HOME', 'TMPDIR', 'TEMP', 'SystemRoot', 'ComSpec'] as const;
export function sanitizedEnvironment(runId: string): NodeJS.ProcessEnv { const env: NodeJS.ProcessEnv = {}; for (const key of inheritedKeys) { const value = process.env[key]; if (value !== undefined) env[key] = value; } env.CI = 'true'; env.ATLAS_FORGE_RUN_ID = runId; env.npm_config_audit = 'false'; env.npm_config_fund = 'false'; return env; }
export type ForgeLogHandler = (line: string) => void;
export async function runStep(step: ForgeStepDefinition, cwd: string, runId: string, onLog: ForgeLogHandler): Promise<ForgeStepResult> {
  const startedAt = new Date().toISOString(); return await new Promise((resolveResult) => { let settled = false, timedOut = false, spawnFailure = false; const child = spawn(step.command, [...step.args], { cwd, env: sanitizedEnvironment(runId), shell: false, stdio: ['ignore', 'pipe', 'pipe'] }); const emit = (prefix: string, chunk: Buffer | string) => { for (const line of chunk.toString().replaceAll('\0', '').split(/\r?\n/)) if (line) onLog(`[${step.id}:${prefix}] ${line}`); }; child.stdout?.on('data', (chunk) => emit('stdout', chunk)); child.stderr?.on('data', (chunk) => emit('stderr', chunk)); const timer = setTimeout(() => { timedOut = true; child.kill('SIGTERM'); setTimeout(() => { if (!settled) child.kill('SIGKILL'); }, 250).unref(); }, step.timeoutMs); timer.unref(); child.on('error', (error) => { spawnFailure = true; onLog(`[${step.id}:infrastructure] ${error.message}`); }); child.on('close', (code) => { if (settled) return; settled = true; clearTimeout(timer); const status: ForgeStepResult['status'] = timedOut ? 'timed_out' : spawnFailure ? 'infrastructure_error' : code === 0 ? 'passed' : 'failed'; resolveResult({ stepId: step.id, status, exitCode: typeof code === 'number' ? code : null, startedAt, finishedAt: new Date().toISOString() }); }); });
}
export async function executePipeline(pipeline: ForgePipelineDefinition, cwd: string, runId: string, onLog: ForgeLogHandler): Promise<{ status: ForgeRunStatus; stepResults: ForgeStepResult[] }> { const stepResults: ForgeStepResult[] = []; for (const step of pipeline.steps) { onLog(`[${step.id}] starting`); const result = await runStep(step, cwd, runId, onLog); stepResults.push(result); onLog(`[${step.id}] ${result.status}`); if (result.status !== 'passed') return { status: result.status, stepResults }; } return { status: 'passed', stepResults }; }
export class ForgeApiClient {
  private readonly baseUrl: string; private readonly runnerToken: string; constructor(baseUrl: string, runnerToken: string) { this.baseUrl = baseUrl.replace(/\/$/, ''); this.runnerToken = runnerToken; }
  private async request(path: string, init: RequestInit): Promise<any> { const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers: { authorization: `Bearer ${this.runnerToken}`, 'content-type': 'application/json', ...(init.headers ?? {}) } }); if (response.status === 204) return null; const text = await response.text(); if (!response.ok) throw new Error(`Forge API ${response.status}: ${text.slice(0, 4096)}`); return text ? JSON.parse(text) : null; }
  async claim(runnerId: string): Promise<ForgeJobRecord | null> { const value = await this.request('/v1/jobs/claim', { method: 'POST', body: JSON.stringify({ runnerId }) }); return value?.job ?? null; }
  async start(jobId: string, runnerId: string): Promise<void> { await this.request(`/v1/jobs/${jobId}/start`, { method: 'POST', body: JSON.stringify({ runnerId }) }); }
  async appendLog(jobId: string, runnerId: string, line: string): Promise<void> { await this.request(`/v1/jobs/${jobId}/log`, { method: 'POST', body: JSON.stringify({ runnerId, line }) }); }
  async complete(jobId: string, runnerId: string, result: { status: ForgeRunStatus; stepResults: readonly ForgeStepResult[]; artifact: ForgeArtifactRecord | null }): Promise<void> { await this.request(`/v1/jobs/${jobId}/complete`, { method: 'POST', body: JSON.stringify({ runnerId, ...result }) }); }
}
export async function executeClaimedJob(job: ForgeJobRecord, config: { client: ForgeApiClient; runnerId: string; home: string; repositoriesRoot: string }): Promise<void> {
  const workspace = join(config.home, 'workspaces', job.id), repository = join(config.repositoriesRoot, `${job.repositoryId}.git`), logs: Promise<void>[] = []; const log = (line: string) => { logs.push(config.client.appendLog(job.id, config.runnerId, line)); }; let started = false; let stepResults: ForgeStepResult[] = [];
  try { await config.client.start(job.id, config.runnerId); started = true; await checkoutExactSha(repository, job.sourceSha, workspace); log(`[checkout] verified ${job.sourceSha}`); const execution = await executePipeline(job.pipeline, workspace, job.runId, log); stepResults = execution.stepResults; await Promise.all(logs); let artifact: ForgeArtifactRecord | null = null; if (execution.status === 'passed' && job.pipeline.artifactPaths.length > 0) artifact = await new FilesystemArtifactStore(config.home).publishDirectory({ sourceDirectory: join(workspace, job.pipeline.artifactPaths[0]), sourceSha: job.sourceSha, runId: job.runId }); await config.client.complete(job.id, config.runnerId, { status: execution.status, stepResults, artifact }); }
  catch (error) { const message = error instanceof Error ? error.message : String(error); if (started) { try { await config.client.appendLog(job.id, config.runnerId, `[infrastructure] ${message.slice(0, 4096)}`); await config.client.complete(job.id, config.runnerId, { status: 'infrastructure_error', stepResults, artifact: null }); } catch {} } throw error; }
  finally { await rm(workspace, { recursive: true, force: true }); }
}
export type ForgeDaemonConfig = { apiUrl: string; runnerToken: string; runnerId: string; home: string; repositoriesRoot: string; pollMs?: number; once?: boolean };
export async function runDaemon(config: ForgeDaemonConfig): Promise<void> { const client = new ForgeApiClient(config.apiUrl, config.runnerToken), pollMs = config.pollMs ?? 2000; let stopping = false; const stop = () => { stopping = true; }; process.once('SIGTERM', stop); process.once('SIGINT', stop); try { while (!stopping) { const job = await client.claim(config.runnerId); if (job) await executeClaimedJob(job, { client, runnerId: config.runnerId, home: config.home, repositoriesRoot: config.repositoriesRoot }); if (config.once) return; if (!job) await new Promise((resolveWait) => setTimeout(resolveWait, pollMs)); } } finally { process.removeListener('SIGTERM', stop); process.removeListener('SIGINT', stop); } }
const execFileAsync = promisify(execFile);
export async function runLocalCi(cwd = process.cwd()): Promise<number> { const sourceSha = (await execFileAsync('git', ['-C', cwd, 'rev-parse', 'HEAD'])).stdout.trim().toLowerCase(); if (!/^[0-9a-f]{40}$/.test(sourceSha)) throw new Error('Current Git HEAD did not resolve to an exact SHA'); const pipeline = parsePipeline(JSON.parse(await readFile(join(cwd, '.atlas', 'forge', 'pipelines', 'atlas-ci.json'), 'utf8'))), runId = randomUUID(), logs: string[] = [], execution = await executePipeline(pipeline, cwd, runId, (line) => { logs.push(line); console.log(line); }), home = resolve(cwd, process.env.ATLAS_FORGE_HOME ?? '.atlas-forge'), runs = join(home, 'local-runs'); await mkdir(runs, { recursive: true, mode: 0o700 }); await writeFile(join(runs, `${runId}.json`), JSON.stringify({ runId, sourceSha, pipelineId: pipeline.id, pipelineVersion: pipeline.version, status: execution.status, stepResults: execution.stepResults, logs }, null, 2), { mode: 0o600 }); return execution.status === 'passed' ? 0 : 1; }
if (import.meta.url === `file://${process.argv[1]}`) { if (process.argv.includes('--local-ci')) { process.exitCode = await runLocalCi(); } else { const home = process.env.ATLAS_FORGE_HOME ?? '.atlas-forge'; const config: ForgeDaemonConfig = { apiUrl: process.env.ATLAS_FORGE_API_URL ?? 'http://127.0.0.1:8788', runnerToken: process.env.ATLAS_FORGE_RUNNER_TOKEN ?? '', runnerId: process.env.ATLAS_FORGE_RUNNER_ID ?? 'runner-primary', home, repositoriesRoot: process.env.ATLAS_FORGE_REPOSITORIES_ROOT ?? `${home}/repos`, once: process.argv.includes('--once') }; if (config.runnerToken.length < 32) throw new Error('ATLAS_FORGE_RUNNER_TOKEN must be at least 32 characters'); await runDaemon(config); } }
