import { type FormEvent, type ReactNode, useCallback, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, Route, Routes } from 'react-router-dom';
import { RequireAtlasIdentity } from '../../identity/RequireAtlasIdentity';
import { loadPayrollWorkspace, payrollMutations, type PayrollCapabilityState, type PayrollWorkspace } from './payrollApi';
import { loadPayrollOperations, payrollOperationsMutations, type PayrollOperations } from './payrollOperationsApi';
import './payroll.css';

type State={status:'loading'}|{status:'error';message:string}|{status:'ready';data:PayrollWorkspace};
type OperationsState={status:'loading'}|{status:'error';message:string}|{status:'ready';data:PayrollOperations};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});

function usePayroll(){const [state,setState]=useState<State>({status:'loading'});const reload=useCallback(()=>{setState({status:'loading'});void loadPayrollWorkspace().then(data=>setState({status:'ready',data})).catch(e=>setState({status:'error',message:e instanceof Error?e.message:'payroll_unavailable'}));},[]);useEffect(reload,[reload]);return {state,reload};}
function usePayrollOperations(){const [state,setState]=useState<OperationsState>({status:'loading'});const reload=useCallback(()=>{setState({status:'loading'});void loadPayrollOperations().then(data=>setState({status:'ready',data})).catch(e=>setState({status:'error',message:e instanceof Error?e.message:'payroll_operations_unavailable'}));},[]);useEffect(reload,[reload]);return {state,reload};}
function Frame({children}:{children:ReactNode}){return <section className="payroll-page page-stack"><header className="payroll-section-header"><p className="payroll-kicker">ATLAS PAYROLL</p><h1>Payroll</h1><p>Governed payroll preparation, deterministic tax calculation and evidence-gated execution.</p><nav className="module-experience-actions"><Link to="/payroll">Overview</Link><Link to="/payroll/people">People</Link><Link to="/payroll/time-earnings">Time & Earnings</Link><Link to="/payroll/pay-runs">Pay Runs</Link><Link to="/payroll/operations">Operations</Link></nav></header>{children}</section>}
function View({state,children}:{state:State;children:(d:PayrollWorkspace)=>ReactNode}){if(state.status==='loading')return <div className="payroll-section-empty" role="status">Loading authorized payroll records…</div>;if(state.status==='error')return <div className="payroll-section-empty" role="alert"><strong>Payroll unavailable</strong><p>{state.message}</p><small>No simulated payroll data is substituted.</small></div>;return <>{children(state.data)}</>}
function CapabilityCard({label,state}:{label:string;state:PayrollCapabilityState}){return <article className="module-experience-card is-active"><strong>{label}</strong><p>{state.status==='ready'?'Ready':'Blocked'}</p><small>{state.reason}</small></article>}

function Overview(){const {state}=usePayroll();return <Frame><View state={state}>{d=>{const active=d.runs.find(r=>!['locked','void'].includes(r.status));const total=d.lines.filter(l=>active&&l.run_id===active.id).reduce((n,l)=>n+l.net_pay,0);const c=d.readiness.capabilities;return <><div className="metric-grid"><article><span>Workers</span><strong>{d.workers.filter(w=>w.status==='active').length}</strong></article><article><span>Pay runs</span><strong>{d.runs.length}</strong></article><article><span>Current net</span><strong>{money.format(total)}</strong></article><article><span>Execution</span><strong>Evidence-gated</strong></article></div><div className="module-experience-grid"><CapabilityCard label="Tax determination" state={c.tax_determination}/><CapabilityCard label="Tax filing" state={c.tax_filing}/><CapabilityCard label="Tax remittance" state={c.tax_remittance}/><CapabilityCard label="Direct deposit" state={c.direct_deposit}/></div></>}}</View></Frame>}
function People(){const {state}=usePayroll();return <Frame><View state={state}>{d=><div className="module-experience-grid">{d.workers.map(w=><article className="module-experience-card is-active" key={w.id}><strong>{w.full_name}</strong><p>{w.job_title||'No job title'} · {w.worker_type}</p><small>{w.status}</small></article>)}</div>}</View></Frame>}
function TimeEarnings(){const {state}=usePayroll();return <Frame><View state={state}>{d=><><div className="status-card"><strong>Approved time is a payroll input</strong><p>Overtime and tax treatment remain governed inputs; ATLAS does not invent legal classifications.</p></div><div className="module-experience-grid">{d.timeEntries.map(t=><article className="module-experience-card is-active" key={t.id}><strong>{d.workers.find(w=>w.id===t.worker_id)?.full_name||'Worker'}</strong><p>{t.work_date} · {t.status}</p></article>)}</div></>}</View></Frame>}

function PayRuns(){
 const {state,reload}=usePayroll();const [error,setError]=useState('');const [selectedRun,setSelectedRun]=useState('');
 const activeRun=useMemo(()=>state.status==='ready'?(state.data.runs.find(r=>r.id===selectedRun)||state.data.runs[0]):undefined,[state,selectedRun]);
 async function createRun(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);setError('');try{await payrollMutations.createRun({scheduleId:String(f.get('scheduleId')||''),periodStart:String(f.get('periodStart')),periodEnd:String(f.get('periodEnd')),payDate:String(f.get('payDate'))});form.reset();reload()}catch(x){setError(x instanceof Error?x.message:'run_create_failed')}}
 async function addLine(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!activeRun)return;const f=new FormData(e.currentTarget);const mode=String(f.get('mode'));setError('');try{await payrollMutations.upsertLine({runId:activeRun.id,workerId:String(f.get('workerId')),regularHours:Number(f.get('regularHours')||0),overtimeHours:Number(f.get('overtimeHours')||0),hourlyRate:mode==='hourly'?Number(f.get('rate')||0):undefined,salaryPeriodAmount:mode==='salary'?Number(f.get('rate')||0):undefined,pretaxDeductions:Number(f.get('pretax')||0),taxesWithheld:Number(f.get('tax')||0),posttaxDeductions:Number(f.get('posttax')||0)});reload()}catch(x){setError(x instanceof Error?x.message:'line_save_failed')}}
 return <Frame><View state={state}>{d=><><form className="atlas-form" onSubmit={createRun}><h2>Create pay run</h2><label>Schedule<select name="scheduleId"><option value="">No schedule</option>{d.schedules.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Period start<input name="periodStart" type="date" required/></label><label>Period end<input name="periodEnd" type="date" required/></label><label>Pay date<input name="payDate" type="date" required/></label><button>Create run</button></form>{d.runs.length?<><label>Selected run<select value={activeRun?.id||''} onChange={e=>setSelectedRun(e.target.value)}>{d.runs.map(r=><option value={r.id} key={r.id}>{r.period_start}–{r.period_end} · {r.status}</option>)}</select></label>{activeRun&&['draft','calculated'].includes(activeRun.status)?<form className="atlas-form" onSubmit={addLine}><h2>Add / update worker line</h2><label>Worker<select name="workerId">{d.workers.filter(w=>w.status==='active').map(w=><option value={w.id} key={w.id}>{w.full_name}</option>)}</select></label><label>Mode<select name="mode"><option value="hourly">Hourly</option><option value="salary">Salary period</option></select></label><label>Rate / salary-period amount<input name="rate" type="number" step="0.01" min="0" required/></label><label>Regular hours<input name="regularHours" type="number" step="0.01" min="0" defaultValue="0"/></label><label>Overtime hours<input name="overtimeHours" type="number" step="0.01" min="0" defaultValue="0"/></label><label>Pre-tax deductions<input name="pretax" type="number" step="0.01" min="0" defaultValue="0"/></label><label>Taxes withheld (manual fallback)<input name="tax" type="number" step="0.01" min="0" defaultValue="0"/></label><label>Post-tax deductions<input name="posttax" type="number" step="0.01" min="0" defaultValue="0"/></label><button>Save line</button></form>:null}<div className="module-experience-grid">{d.lines.filter(l=>l.run_id===activeRun?.id).map(l=><article className="module-experience-card is-active" key={l.id}><strong>{d.workers.find(w=>w.id===l.worker_id)?.full_name||'Worker'}</strong><p>Gross {money.format(l.gross_pay)} · Net {money.format(l.net_pay)}</p><small>Taxes {money.format(l.taxes_withheld)}</small></article>)}</div>{activeRun?<div className="atlas-action-row">{activeRun.status==='draft'?<button onClick={()=>void payrollMutations.transitionRun(activeRun.id,'calculate').then(reload)}>Calculate</button>:null}{activeRun.status==='calculated'?<button onClick={()=>void payrollMutations.transitionRun(activeRun.id,'approve').then(reload)}>Approve</button>:null}{activeRun.status==='approved'?<button onClick={()=>void payrollMutations.transitionRun(activeRun.id,'lock').then(reload)}>Lock</button>:null}</div>:null}</>:<p>No pay runs yet.</p>}{error?<p role="alert">{error}</p>:null}</>}</View></Frame>
}

function PayrollOperations(){
 const {state:payrollState,reload:reloadPayroll}=usePayroll();const {state:opsState,reload}=usePayrollOperations();const [error,setError]=useState('');const [notice,setNotice]=useState('');
 async function save(form:HTMLFormElement|undefined,action:()=>Promise<unknown>,message='Saved with governed audit controls.'){setError('');setNotice('');try{await action();form?.reset();setNotice(message);reload();reloadPayroll()}catch(x){setError(x instanceof Error?x.message:'payroll_operation_failed')}}
 return <Frame><View state={payrollState}>{d=>{if(opsState.status==='loading')return <div className="payroll-section-empty" role="status">Loading payroll operations…</div>;if(opsState.status==='error')return <div className="payroll-section-empty" role="alert">{opsState.message}</div>;const o=opsState.data;const workers=d.workers.filter(w=>w.status==='active');const runs=d.runs.filter(r=>r.status!=='void');const workerName=(id:string|null)=>d.workers.find(w=>w.id===id)?.full_name||'Worker';return <>
  <div className="status-card"><strong>Execution boundary</strong><p>Preparing a filing, remittance or payment does not execute it. Submitted, accepted and settled require authenticated provider evidence.</p></div>

  <section className="page-stack"><h2>Federal W-4 & tax determination</h2><p>2026 standard employees, regular wages, W-4 2020+ only. Unsupported cases fail closed.</p>
   <form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.recordFederalW4({workerId:String(f.get('workerId')),formYear:Number(f.get('formYear')),filingStatus:String(f.get('filingStatus')),step2Checkbox:f.get('step2')==='on',step3Credits:Number(f.get('step3')||0),step4aOtherIncome:Number(f.get('step4a')||0),step4bDeductions:Number(f.get('step4b')||0),step4cExtraWithholding:Number(f.get('step4c')||0),exempt:f.get('exempt')==='on',nonresidentAlien:false,effectiveFrom:String(f.get('effectiveFrom')),sourceEvidenceHash:String(f.get('evidenceHash'))}),'W-4 evidence recorded.');}}><h3>Record W-4 election</h3><label>Worker<select name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Form year<input name="formYear" type="number" min="2020" defaultValue="2026" required/></label><label>Filing status<select name="filingStatus"><option value="single_or_married_filing_separately">Single / married filing separately</option><option value="married_filing_jointly">Married filing jointly</option><option value="head_of_household">Head of household</option></select></label><label><input name="step2" type="checkbox"/> Step 2 checkbox</label><label>Step 3 credits<input name="step3" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Step 4(a) other income<input name="step4a" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Step 4(b) deductions<input name="step4b" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Step 4(c) extra withholding<input name="step4c" type="number" min="0" step="0.01" defaultValue="0"/></label><label><input name="exempt" type="checkbox"/> Exempt from FIT</label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>W-4 evidence hash<input name="evidenceHash" required/></label><button>Record W-4</button></form>
   <form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const runId=String(f.get('runId'));const workerId=String(f.get('workerId'));void save(undefined,async()=>{const determinationId=await payrollOperationsMutations.determineFederal2026({runId,workerId,ytdSocialSecurityWages:Number(f.get('ytdSs')||0),ytdMedicareWages:Number(f.get('ytdMedicare')||0),ytdFutaWages:Number(f.get('ytdFuta')||0),ytdEvidenceHash:String(f.get('ytdEvidence')||'')});await payrollOperationsMutations.applyFederalTaxToLine({runId,workerId,determinationId})},'Federal determination created and applied to the payroll line.');}}><h3>Apply federal tax to line</h3><label>Run<select name="runId" required>{runs.filter(r=>['draft','calculated'].includes(r.status)).map(r=><option key={r.id} value={r.id}>{r.pay_date} · {r.status}</option>)}</select></label><label>Worker<select name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>YTD Social Security wages<input name="ytdSs" type="number" min="0" step="0.01" defaultValue="0"/></label><label>YTD Medicare wages<input name="ytdMedicare" type="number" min="0" step="0.01" defaultValue="0"/></label><label>YTD FUTA wages<input name="ytdFuta" type="number" min="0" step="0.01" defaultValue="0"/></label><label>YTD evidence hash<input name="ytdEvidence" placeholder="Required when any YTD amount is non-zero"/></label><button>Apply federal tax to line</button></form>
  </section>

  <section className="page-stack"><h2>Jurisdictions</h2><div className="module-experience-grid">{o.workerJurisdictions.map(j=><article className="module-experience-card is-active" key={j.id}><strong>{workerName(j.worker_id)}</strong><p>{j.residence_state} residence · {j.work_state} work</p><small>{j.remote_work?'Remote work':'On-site'}{j.local_code?` · ${j.local_code}`:''}</small></article>)}</div>
   <form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.upsertWorkerJurisdiction({workerId:String(f.get('workerId')),residenceState:String(f.get('residenceState')),workState:String(f.get('workState')),effectiveFrom:String(f.get('effectiveFrom')),evidenceHash:String(f.get('evidenceHash')),localCode:String(f.get('localCode')||''),remoteWork:f.get('remoteWork')==='on'}));}}><h3>Worker jurisdiction</h3><label>Worker<select name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Residence state<input name="residenceState" maxLength={2} required/></label><label>Work state<input name="workState" maxLength={2} required/></label><label>Local code<input name="localCode"/></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Evidence hash<input name="evidenceHash" required/></label><label><input name="remoteWork" type="checkbox"/> Remote work</label><button>Save jurisdiction</button></form>
   <form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.upsertEmployerTaxProfile({stateCode:'FL',taxKind:'reemployment',employerRate:Number(f.get('rate')),wageBase:7000,effectiveFrom:String(f.get('effectiveFrom')),evidenceHash:String(f.get('evidenceHash')),sourceUri:'https://floridarevenue.com/taxes/taxesfees/Pages/rt_rate.aspx'}));}}><h3>Florida reemployment tax profile</h3><p>Enter the employer-specific Florida DOR rate. The 2.7% field default is the statutory new-employer rate, not a claim about your account.</p><label>Employer rate<input name="rate" type="number" min="0.001" max="0.054" step="0.0001" defaultValue="0.027" required/></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Rate evidence hash<input name="evidenceHash" required/></label><button>Save Florida rate</button></form>
  </section>

  <section className="page-stack"><h2>Benefits & deductions</h2><div className="module-experience-grid">{o.workerDeductions.map(x=>{const def=o.deductionDefinitions.find(v=>v.id===x.deduction_definition_id);return <article className="module-experience-card is-active" key={x.id}><strong>{workerName(x.worker_id)}</strong><p>{def?.name||'Deduction'} · {x.amount_type} {x.amount}</p><small>{def?.taxability||'unclassified'}</small></article>})}</div><form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.upsertWorkerDeduction({workerId:String(f.get('workerId')),code:String(f.get('code')),name:String(f.get('name')),category:String(f.get('category')),taxability:String(f.get('taxability')),amountType:String(f.get('amountType')),amount:Number(f.get('amount')),effectiveFrom:String(f.get('effectiveFrom')),evidenceHash:String(f.get('evidenceHash'))}));}}><label>Worker<select name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Code<input name="code" required/></label><label>Name<input name="name" required/></label><label>Category<select name="category"><option value="health">Health</option><option value="retirement">Retirement</option><option value="benefit">Benefit</option><option value="other">Other</option></select></label><label>Taxability<select name="taxability"><option value="unclassified">Unclassified — blocks tax automation</option><option value="pretax_fit_fica">Pre-tax FIT/FICA</option><option value="pretax_fit_only">Pre-tax FIT only</option><option value="posttax">Post-tax</option></select></label><label>Amount type<select name="amountType"><option value="fixed">Fixed</option><option value="percent">Percent</option></select></label><label>Amount<input name="amount" type="number" step="0.01" min="0" required/></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Evidence hash<input name="evidenceHash" required/></label><button>Save deduction</button></form></section>

  <section className="page-stack"><h2>Garnishments</h2><div className="module-experience-grid">{o.garnishments.map(g=><article className="module-experience-card is-active" key={g.id}><strong>{workerName(g.worker_id)}</strong><p>{g.order_type} · {g.authority}</p><small>{g.case_reference} · priority {g.priority} · {g.status}</small></article>)}</div><form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.recordGarnishment({workerId:String(f.get('workerId')),orderType:String(f.get('orderType')),authority:String(f.get('authority')),caseReference:String(f.get('caseReference')),amountType:String(f.get('amountType')),amount:Number(f.get('amount')),priority:Number(f.get('priority')),effectiveFrom:String(f.get('effectiveFrom')),evidenceHash:String(f.get('evidenceHash'))}));}}><label>Worker<select name="workerId" required>{workers.map(w=><option key={w.id} value={w.id}>{w.full_name}</option>)}</select></label><label>Order type<input name="orderType" required/></label><label>Authority<input name="authority" required/></label><label>Case reference<input name="caseReference" required/></label><label>Amount type<select name="amountType"><option value="fixed">Fixed</option><option value="percent">Percent</option></select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required/></label><label>Priority<input name="priority" type="number" min="1" defaultValue="100" required/></label><label>Effective from<input name="effectiveFrom" type="date" required/></label><label>Order evidence hash<input name="evidenceHash" required/></label><button>Record order</button></form></section>

  <section className="page-stack"><h2>Compliance queue</h2><div className="module-experience-grid">{o.compliance.map(c=><article className="module-experience-card is-active" key={c.id}><strong>{c.form_code||c.obligation_type}</strong><p>{c.jurisdiction} · due {c.due_date}</p><small>{c.execution_status}{c.amount!=null?` · ${money.format(c.amount)}`:''}</small></article>)}</div><form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.createComplianceObligation({runId:String(f.get('runId')||''),jurisdiction:String(f.get('jurisdiction')),obligationType:String(f.get('obligationType')),formCode:String(f.get('formCode')||''),dueDate:String(f.get('dueDate')),amount:f.get('amount')?Number(f.get('amount')):undefined,providerConnectionId:String(f.get('provider')||'')}));}}><label>Run<select name="runId"><option value="">Not run-specific</option>{runs.map(r=><option key={r.id} value={r.id}>{r.pay_date} · {r.status}</option>)}</select></label><label>Jurisdiction<input name="jurisdiction" defaultValue="US-FEDERAL" required/></label><label>Type<select name="obligationType"><option value="tax.file">Tax filing</option><option value="tax.remit">Tax remittance</option><option value="year_end.forms">Year-end forms</option><option value="state.report">State report</option></select></label><label>Form code<input name="formCode" placeholder="941 / 940 / W-2 / RT-6"/></label><label>Due date<input name="dueDate" type="date" required/></label><label>Amount<input name="amount" type="number" min="0" step="0.01"/></label><label>Verified provider<select name="provider"><option value="">None — prepare only</option>{o.providers.filter(p=>p.status==='verified'&&p.environment==='production').map(p=><option key={p.id} value={p.id}>{p.provider_key}</option>)}</select></label><button>Prepare obligation</button></form></section>

  <section className="page-stack"><h2>Payment batches</h2><div className="module-experience-grid">{o.paymentBatches.map(b=><article className="module-experience-card is-active" key={b.id}><strong>{b.payment_kind.toUpperCase()}</strong><p>{money.format(b.amount)}</p><small>{b.execution_status}</small></article>)}</div><form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.createPaymentBatch({runId:String(f.get('runId')),paymentKind:String(f.get('kind')),amount:Number(f.get('amount')),providerConnectionId:String(f.get('provider')||'')}));}}><label>Run<select name="runId" required>{runs.map(r=><option key={r.id} value={r.id}>{r.pay_date} · {r.status}</option>)}</select></label><label>Kind<select name="kind"><option value="ach">ACH</option><option value="paycard">Pay card</option><option value="check">Check</option></select></label><label>Amount<input name="amount" type="number" min="0" step="0.01" required/></label><label>Verified provider<select name="provider"><option value="">None — prepare only</option>{o.providers.filter(p=>p.status==='verified'&&p.environment==='production').map(p=><option key={p.id} value={p.id}>{p.provider_key}</option>)}</select></label><button>Prepare payment batch</button></form></section>

  <section className="page-stack"><h2>GL postings</h2><div className="module-experience-grid">{o.glPostings.map(g=><article className="module-experience-card is-active" key={g.id}><strong>{g.journal_ref}</strong><p>Debit {money.format(g.debit_total)} · Credit {money.format(g.credit_total)}</p><small>{g.status}</small></article>)}</div><form className="atlas-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void save(form,()=>payrollOperationsMutations.recordGlPosting({runId:String(f.get('runId')),journalRef:String(f.get('journalRef')),debitTotal:Number(f.get('debit')),creditTotal:Number(f.get('credit')),status:String(f.get('status')),evidenceHash:String(f.get('evidenceHash')||'')}));}}><label>Run<select name="runId" required>{runs.map(r=><option key={r.id} value={r.id}>{r.pay_date} · {r.status}</option>)}</select></label><label>Journal reference<input name="journalRef" required/></label><label>Debit total<input name="debit" type="number" min="0" step="0.01" required/></label><label>Credit total<input name="credit" type="number" min="0" step="0.01" required/></label><label>Status<select name="status"><option value="draft">Draft</option><option value="posted">Posted — evidence required</option><option value="failed">Failed</option></select></label><label>Posting evidence hash<input name="evidenceHash"/></label><button>Record GL posting</button></form></section>

  <section className="page-stack"><h2>Variance review</h2><div className="atlas-action-row">{runs.map(r=><button key={r.id} onClick={()=>void save(undefined,()=>payrollOperationsMutations.scanRunVariances(r.id),'Variance scan completed.')}>Scan {r.pay_date}</button>)}</div><div className="module-experience-grid">{o.varianceFindings.map(v=><article className="module-experience-card is-active" key={v.id}><strong>{v.finding_type.replaceAll('_',' ')}</strong><p>{workerName(v.worker_id)} · {v.severity}</p><small>{v.delta_percent!=null?`${v.delta_percent}% · `:''}{v.requires_review?'requires review':'reviewed'} · {v.status}</small></article>)}</div></section>
  {notice?<p role="status">{notice}</p>:null}{error?<p role="alert">{error}</p>:null}
 </>}}</View></Frame>
}

export function PayrollRoutes(){return <RequireAtlasIdentity><Routes><Route index element={<Overview/>}/><Route path="overview" element={<Navigate to="/payroll" replace/>}/><Route path="people" element={<People/>}/><Route path="time-earnings" element={<TimeEarnings/>}/><Route path="pay-runs" element={<PayRuns/>}/><Route path="operations" element={<PayrollOperations/>}/></Routes></RequireAtlasIdentity>}
