const RISK_LEVELS=new Set(['LOW','MEDIUM','HIGH','CRITICAL']);
const OPERATION_TYPES=new Set(['READ','WRITE']);
function requireText(value,name){if(typeof value!=='string'||!value.trim()) throw new TypeError(`${name}_required`);return value.trim();}
function clone(value){return value===undefined?undefined:structuredClone(value);}
function permissionsOf(context){return Array.isArray(context?.permissions)?context.permissions:[];}
function hasPermission(context,permission){const permissions=permissionsOf(context);return permissions.includes('*')||permissions.includes(permission);}
function createDenied(code,status=403,details={}){return Object.assign(new Error(code),{code,status,...details});}
export function validateAgentContext(context={}){const errors=[];if(typeof context.organization_id!=='string'||!context.organization_id.trim())errors.push('organization_id_required');if(typeof context.user_id!=='string'||!context.user_id.trim())errors.push('user_id_required');if(!Array.isArray(context.permissions))errors.push('permissions_required');if(typeof context.session_id!=='string'||!context.session_id.trim())errors.push('session_id_required');if(typeof context.request_id!=='string'||!context.request_id.trim())errors.push('request_id_required');return {ok:errors.length===0,errors};}
export function normalizeAgentContext(context={}){const validation=validateAgentContext(context);if(!validation.ok)throw createDenied(`invalid_agent_context:${validation.errors.join(',')}`,400,{errors:validation.errors});return Object.freeze({organization_id:context.organization_id.trim(),user_id:context.user_id.trim(),permissions:[...new Set(context.permissions.map(String))],roles:Array.isArray(context.roles)?[...new Set(context.roles.map(String))]:[],session_id:context.session_id.trim(),request_id:context.request_id.trim(),actor_type:'human',...(context.agent_id?{agent_id:String(context.agent_id)}:{}),...(context.channel?{channel:String(context.channel)}:{})});}
export class AtlasToolRegistry{#tools=new Map();register(tool={}){const name=requireText(tool.name,'tool_name'),module=requireText(tool.module,'tool_module'),operation=requireText(tool.operation,'tool_operation').toUpperCase(),risk_level=requireText(tool.risk_level||'LOW','tool_risk_level').toUpperCase();if(!OPERATION_TYPES.has(operation))throw new TypeError('invalid_tool_operation');if(!RISK_LEVELS.has(risk_level))throw new TypeError('invalid_tool_risk_level');if(typeof tool.handler!=='function')throw new TypeError('tool_handler_required');if(this.#tools.has(name))throw Object.assign(new Error('tool_already_registered'),{code:'tool_already_registered',status:409,name});const normalized=Object.freeze({name,module,operation,risk_level,description:String(tool.description||''),permission:requireText(tool.permission,'tool_permission'),requires_approval:Boolean(tool.requires_approval||risk_level==='HIGH'||risk_level==='CRITICAL'),input_schema:clone(tool.input_schema||{type:'object'}),handler:tool.handler});this.#tools.set(name,normalized);return {...normalized,handler:undefined};}get(name){return this.#tools.get(name)||null;}list(){return [...this.#tools.values()].map(tool=>({...tool,handler:undefined}));}}
export class AtlasAgentPolicyGateway{evaluate({context,tool,arguments:args={}}={}){const normalized=normalizeAgentContext(context);if(!tool)return {allowed:false,reason:'tool_not_found',context:normalized};if(!hasPermission(normalized,tool.permission))return {allowed:false,reason:'permission_denied',context:normalized};if(args&&typeof args==='object'&&'organization_id' in args&&args.organization_id!==normalized.organization_id)return {allowed:false,reason:'tenant_mismatch',context:normalized};return {allowed:true,reason:'allowed',context:normalized};}}
export class AtlasAgenticDispatcher{#registry;#policy;#approvals;#audit;constructor({registry,policy,approvals,audit}={}){if(!registry)throw new TypeError('registry_required');if(!policy)throw new TypeError('policy_required');if(!audit)throw new TypeError('audit_required');this.#registry=registry;this.#policy=policy;this.#approvals=approvals;this.#audit=audit;}async execute({context,tool_name,arguments:args={},approval_id=null}={}){const tool=this.#registry.get(tool_name),evaluation=this.#policy.evaluate({context,tool,arguments:args}),normalized=evaluation.context,baseAudit={context:normalized,target_type:'agent_tool',target_id:String(tool_name||'unknown')};if(!evaluation.allowed){this.#audit.append({...baseAudit,action:'agent.tool.rejected',details:{request_id:normalized.request_id,reason:evaluation.reason}});throw createDenied(evaluation.reason,403,{tool_name});}if(tool.requires_approval){if(!this.#approvals)throw createDenied('approval_service_unavailable',503,{tool_name});if(!approval_id){this.#audit.append({...baseAudit,action:'agent.tool.awaiting_approval',details:{request_id:normalized.request_id,risk_level:tool.risk_level}});throw createDenied('approval_required',409,{tool_name});}const approvals=this.#approvals.list({context:normalized}),approval=approvals.find(item=>item.id===approval_id&&item.status==='approved'&&item.subject_type==='agent_tool'&&item.subject_id===tool.name);if(!approval){this.#audit.append({...baseAudit,action:'agent.tool.rejected',details:{request_id:normalized.request_id,reason:'approval_invalid'}});throw createDenied('approval_invalid',403,{tool_name});}}this.#audit.append({...baseAudit,action:'agent.tool.authorized',details:{request_id:normalized.request_id,module:tool.module,operation:tool.operation,risk_level:tool.risk_level}});try{const result=await tool.handler({context:normalized,arguments:clone(args)});this.#audit.append({...baseAudit,action:'agent.tool.succeeded',details:{request_id:normalized.request_id,module:tool.module}});return result;}catch(error){this.#audit.append({...baseAudit,action:'agent.tool.failed',details:{request_id:normalized.request_id,module:tool.module,error_code:error?.code||'execution_failed'}});throw error;}}}
export function createAtlasAgenticCore({approvals,audit}={}){const registry=new AtlasToolRegistry(),policy=new AtlasAgentPolicyGateway(),dispatcher=new AtlasAgenticDispatcher({registry,policy,approvals,audit});return {registry,policy,dispatcher};}
export const agenticCoreContract=Object.freeze({service:'ATLAS Intelligence & Agentic Core',issue:434,providerNeutral:true,directDatabaseAccess:false,governedToolExecution:true,tenantBoundary:'organization_id',humanPrincipal:'user_id'});
