const DEFAULT_MODEL='gemini-3.8-flash';
const THINKING_LEVEL=Object.freeze({fast:'low',balanced:'medium',deep:'high'});
function fail(code,status=500,details={}){return Object.assign(new Error(code),{code,status,...details});}
async function providerJson(response){let data={};try{data=await response.json()}catch{}return data;}
function textOf(value){if(typeof value==='string')return value;if(value&&typeof value==='object'&&typeof value.text==='string')return value.text;try{return JSON.stringify(value)}catch{return String(value??'')}}
function contentsOf(input=[]){return input.map(item=>({role:item?.role==='assistant'?'model':'user',parts:[{text:textOf(item?.content)}]})).filter(item=>item.parts[0].text);}
function outputText(data){const out=[];for(const candidate of data?.candidates||[])for(const part of candidate?.content?.parts||[])if(part?.text&&part?.thought!==true)out.push(String(part.text));return out.join('\n').trim();}
function errorCode(status){if(status===401||status===403||status===404)return 'provider_not_configured';if(status===429)return 'provider_rate_limited';return 'provider_unavailable';}
export function createGeminiAdapter({apiKey,model=DEFAULT_MODEL,fetchFn=fetch}={}){const resolved=String(model||DEFAULT_MODEL);const descriptor=()=>({id:'gemini',configured:Boolean(apiKey),capabilities:['generation','reasoning'],profiles:['fast','balanced','deep'],api:'generateContent',models:{fast:resolved,balanced:resolved,deep:resolved}});async function probe(){if(!apiKey)return {configured:false,verified:false,provider:'gemini',model:resolved,error:'provider_not_configured'};let response;try{response=await fetchFn(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(resolved)}`,{headers:{'x-goog-api-key':apiKey,'content-type':'application/json'}});}catch{return {configured:true,verified:false,provider:'gemini',model:resolved,error:'provider_unavailable'}}if(!response.ok)return {configured:true,verified:false,provider:'gemini',model:resolved,error:errorCode(response.status)};const data=await providerJson(response);const returned=String(data?.name||'').replace(/^models\//,'');if(returned&&returned!==resolved)return {configured:true,verified:false,provider:'gemini',model:resolved,error:'provider_unavailable'};return {configured:true,verified:true,provider:'gemini',model:resolved,error:null};}async function execute({route,instructions,input,max_output_tokens=3000}={}){if(!apiKey)throw fail('provider_not_configured',503);const profile=route?.profile||'balanced',thinkingLevel=THINKING_LEVEL[profile];if(!thinkingLevel)throw fail('capability_unavailable',409);const body={contents:contentsOf(input),generationConfig:{maxOutputTokens:max_output_tokens,thinkingConfig:{thinkingLevel,includeThoughts:false}}};if(instructions)body.systemInstruction={parts:[{text:String(instructions)}]};let response;try{response=await fetchFn(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(resolved)}:generateContent`,{method:'POST',headers:{'x-goog-api-key':apiKey,'content-type':'application/json'},body:JSON.stringify(body)});}catch{throw fail('provider_unavailable',502)}if(!response.ok){const code=errorCode(response.status);throw fail(code,code==='provider_rate_limited'?429:code==='provider_not_configured'?503:502)}const data=await providerJson(response),text=outputText(data);if(!text)throw fail('internal_error',500);return {provider:'gemini',model:data.modelVersion||resolved,response_id:data.responseId||null,text,capabilities_used:[...(route?.capabilities||['generation'])],usage:data.usageMetadata||{},provenance:[]};}return Object.freeze({descriptor,probe,execute});}
