import {createIntelligenceGateway,createIntelligenceRouter,normalizeIntelligenceError} from './intelligence-gateway.mjs';
import {resolveIntelligenceContext} from './atlas-intelligence-auth.mjs';
import {createIntelligenceStore} from './atlas-intelligence-store.mjs';
import {createOpenAIResponsesAdapter} from './openai-responses-adapter.mjs';
import {createGeminiAdapter} from './gemini-adapter.mjs';
import {renderAtlasCopilotPage} from './ui.mjs';

const U='https://ggmanzcgtlrvqfoccgsh.supabase.co';
const K='sb_publishable_wicVjdsduxa5FAnRW9k0Lw_HxtBW72d';
const LIVE='/functions/v1/atlas-live';
const SELF='/functions/v1/atlas-copilot';
const REPAIR='/functions/v1/atlas-repair-bridge';
const VERSION=5;
const ASTRA_MODEL=Deno.env.get('ATLAS_OPENAI_ASTRA_MODEL')||'gpt-6-astra';
const GEMINI_MODEL=Deno.env.get('ATLAS_GEMINI_MODEL')||'gemini-3.8-flash';
const OPENAI_MODELS={fast:ASTRA_MODEL,balanced:ASTRA_MODEL,deep:ASTRA_MODEL};
const PROVIDER_IDS=new Set(['openai','gemini']);
function headers(extra={}){return {'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin',...extra};}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:headers({'content-type':'application/json; charset=utf-8'})});}
function safeError(error){const n=normalizeIntelligenceError(error);return json({ok:false,error:n.code,trace_id:error?.trace_id||n.trace_id||null},n.status);}
function authRequest(req,organization_id){if(!organization_id||req.headers.get('x-atlas-org-id'))return req;const h=new Headers(req.headers);h.set('x-atlas-org-id',String(organization_id));return new Request(req.url,{method:req.method,headers:h});}
function runtime(){const serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'',openaiApiKey=Deno.env.get('OPENAI_API_KEY')||'',geminiApiKey=Deno.env.get('GEMINI_API_KEY')||'';return {serviceRoleKey,openaiApiKey,geminiApiKey,storageConfigured:Boolean(serviceRoleKey)};}
async function contextFor(req,organization_id){return resolveIntelligenceContext({request:authRequest(req,organization_id),supabaseUrl:U,publishableKey:K,fetchFn:fetch});}
function storeFor(serviceRoleKey){if(!serviceRoleKey)throw Object.assign(new Error('storage_not_configured'),{code:'storage_not_configured',status:503});return createIntelligenceStore({supabaseUrl:U,serviceRoleKey,fetchFn:fetch});}
function adapterFor(rt,providerId){if(providerId==='openai')return createOpenAIResponsesAdapter({apiKey:rt.openaiApiKey,models:OPENAI_MODELS,fetchFn:fetch});if(providerId==='gemini')return createGeminiAdapter({apiKey:rt.geminiApiKey,model:GEMINI_MODEL,fetchFn:fetch});throw Object.assign(new Error('provider_not_configured'),{code:'provider_not_configured',status:503});}
function stateLabel(probe){return probe.verified?'verified_for_request':probe.error==='provider_unavailable'||probe.error==='provider_rate_limited'?'unavailable':probe.configured?'configured_unverified':'not_configured';}
async function providerState(rt,providerId,profile='balanced'){const adapter=adapterFor(rt,providerId),probe=await adapter.probe({profile});return {state:stateLabel(probe),probe,adapter,descriptor:{...adapter.descriptor(),configured:probe.configured,verified:probe.verified}};}
async function allProviderStates(rt,profile='balanced'){const [openai,gemini]=await Promise.all([providerState(rt,'openai',profile),providerState(rt,'gemini',profile)]);return {openai,gemini};}
function publicProviderState(entry){return {state:entry.state,configured:entry.probe.configured,verified:entry.probe.verified,model:entry.probe.model,error:entry.probe.error,api:entry.descriptor.api,models:entry.descriptor.models};}
async function parseJson(req){try{return await req.json()}catch{throw Object.assign(new Error('invalid_input'),{code:'invalid_input',status:400})}}
async function handleHistory(req){const rt=runtime(),resolved=await contextFor(req),store=storeFor(rt.serviceRoleKey),conversations=await store.listConversations({context:resolved.context});return json({ok:true,conversations});}
async function handleConversation(req,url){const rt=runtime(),resolved=await contextFor(req),id=url.searchParams.get('id');if(!id)return json({ok:false,error:'invalid_input'},400);const store=storeFor(rt.serviceRoleKey),conversation=await store.getConversation({context:resolved.context,id}),messages=await store.listMessages({context:resolved.context,conversation_id:id,limit:50});return json({ok:true,conversation,messages});}
async function handleStatus(req){const rt=runtime(),resolved=await contextFor(req),states=await allProviderStates(rt,'balanced'),openai=states.openai;return json({ok:true,authenticated:true,provider:'openai',provider_state:openai.state,model:openai.probe.model,models:OPENAI_MODELS,providers:{openai:publicProviderState(states.openai),gemini:publicProviderState(states.gemini)},available_providers:Object.entries(states).filter(([,entry])=>entry.probe.verified).map(([id])=>id),storage_state:rt.storageConfigured?'configured':'not_configured',organization:resolved.context.organization_id,role:resolved.context.roles[0]||null,capabilities:['generation','reasoning'],profiles:['fast','balanced','deep'],repositoryMutation:'github-actions-oidc-queue'});}
async function handleChat(req){if(req.method!=='POST')return json({ok:false,error:'method_not_allowed'},405);const body=await parseJson(req),resolved=await contextFor(req,body?.organization_id),rt=runtime(),store=storeFor(rt.serviceRoleKey),message=String(body?.message||'').trim();if(!message)return json({ok:false,error:'invalid_input'},400);const legacy=String(body?.context||'').trim().slice(0,12000),intent=String(body?.intent||'balanced'),providerId=String(body?.provider_id||'openai').trim().toLowerCase();if(!PROVIDER_IDS.has(providerId))return json({ok:false,error:'provider_not_configured',provider:providerId},503);const p=await providerState(rt,providerId,intent);if(!p.probe.verified)return json({ok:false,error:p.probe.error||'provider_unavailable',provider:providerId,provider_state:p.state},p.probe.error==='provider_rate_limited'?429:p.state==='not_configured'?503:502);const router=createIntelligenceRouter({providers:[p.descriptor]});const gateway=createIntelligenceGateway({router,providers:{[providerId]:p.adapter},store});const request=body?.context!==undefined&&body?.module===undefined?{module:'workbench',intent:'balanced',provider_id:providerId,message,capabilities_requested:['generation'],client_metadata:{legacy_context_present:Boolean(legacy)},legacy_context:legacy}:{module:body?.module||'atlas',intent,provider_id:providerId,message,conversation_id:body?.conversation_id||null,capabilities_requested:Array.isArray(body?.capabilities_requested)?body.capabilities_requested:['generation'],client_metadata:body?.client_metadata&&typeof body.client_metadata==='object'?body.client_metadata:{},legacy_context:legacy};const result=await gateway.execute({context:resolved.context,request});return json({ok:true,...result,text:result.output,provider_state:'verified_for_request',execution:{repositoryMutation:false,repairQueue:'available',mode:'analysis'}});}

Deno.serve(async req=>{const url=new URL(req.url),api=url.searchParams.get('api');try{if(api==='readiness'){const rt=runtime(),states=await allProviderStates(rt,'balanced'),openai=states.openai;return json({ok:true,state:'ready',service:'atlas-copilot',version:VERSION,auth:'atlas-session-required-for-prompts',provider:'openai',provider_state:openai.state,model:openai.probe.model,models:OPENAI_MODELS,providers:{openai:publicProviderState(states.openai),gemini:publicProviderState(states.gemini)},available_providers:Object.entries(states).filter(([,entry])=>entry.probe.verified).map(([id])=>id),reasoning_profiles:{fast:'low',balanced:'medium',deep:'high'},storage_state:rt.storageConfigured?'configured':'not_configured',repositoryMutation:'github-actions-oidc-queue',repairBridge:REPAIR,checkedAt:new Date().toISOString()});}if(api==='status')return await handleStatus(req);if(api==='history')return await handleHistory(req);if(api==='conversation')return await handleConversation(req,url);if(api==='chat')return await handleChat(req);const html=renderAtlasCopilotPage({supabaseUrl:U,publishableKey:K,selfPath:SELF,repairPath:REPAIR,livePath:LIVE,version:VERSION});return new Response(html,{headers:headers({'content-type':'text/html; charset=utf-8','content-security-policy':`default-src 'self'; connect-src ${U}; style-src 'unsafe-inline'; script-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'`})});}catch(error){console.error('atlas_ia_request_failed',{code:error?.code||'internal_error'});return safeError(error);}});
