import { Link, Navigate, Route, Routes } from 'react-router-dom';
import { HealthDataNotice } from '../shared/HealthDataNotice';

function ResearchHome() { return <section className="health-stack"><header className="page-header"><p className="eyebrow">ATLAS Health</p><h1>Research & Innovation</h1><p>Governed research workspace with explicit separation between evidence, hypothesis, falsification and cure-level claims.</p></header><HealthDataNotice state="demo" text="Research workspace contains no clinical recommendation or patient-specific data." /><div className="health-entry-grid"><Link className="health-module-card" to="/health/research/frontiers"><span className="health-module-icon">◇</span><span><strong>Health Frontiers</strong><small>Mechanism-centered research and disease reconstruction governance.</small></span><span>→</span></Link><Link className="health-module-card" to="/health/research/evidence"><span className="health-module-icon">◇</span><span><strong>Evidence Registry</strong><small>Track evidence levels, limitations and provenance.</small></span><span>→</span></Link><Link className="health-module-card" to="/health/research/falsification"><span className="health-module-icon">◇</span><span><strong>Falsification Engine</strong><small>Preserve counterexamples and escape routes.</small></span><span>→</span></Link></div></section>; }
function Frontiers() { return <section className="health-stack"><p className="eyebrow">Research & Innovation</p><h1>Health Frontiers</h1><p className="health-copy">A governed research program for persistent disease mechanisms, reconstruction risk and durable-response hypotheses.</p><Link className="health-primary-action" to="/health/research/frontiers/disease-reconstruction">Disease Reconstruction Lab</Link></section>; }
function Reconstruction() { return <section className="health-stack"><p className="eyebrow">Health Frontiers</p><h1>Disease Reconstruction Lab</h1><div className="notice strong">Research-only workspace. The prior uncommitted source package is not represented as restored; this route preserves the governed product boundary without inventing evidence records.</div><div className="health-entry-grid"><div className="health-panel"><h3>Neural Graph</h3><p>Awaiting governed evidence package restoration.</p></div><div className="health-panel"><h3>Vulnerability Engine</h3><p>No synthetic score is generated without a registered model dataset.</p></div><div className="health-panel"><h3>Curability Governance</h3><p>Cure-level claims remain evidence-gated.</p></div></div></section>; }
function Evidence() { return <section className="health-stack"><p className="eyebrow">Research</p><h1>Evidence Registry</h1><div className="empty-state"><strong>No governed evidence records are loaded in this repository snapshot.</strong><span>Register evidence with provenance before analysis.</span></div></section>; }
function Falsification() { return <section className="health-stack"><p className="eyebrow">Research</p><h1>Falsification Engine</h1><div className="empty-state"><strong>No falsification records are loaded.</strong><span>Counterexamples and alternative explanations belong here when the governed dataset is restored.</span></div></section>; }
export function ResearchRoutes() { return <section className="health-page health-stack"><Routes><Route index element={<ResearchHome />} /><Route path="frontiers" element={<Frontiers />} /><Route path="frontiers/disease-reconstruction" element={<Reconstruction />} /><Route path="evidence" element={<Evidence />} /><Route path="falsification" element={<Falsification />} /><Route path="*" element={<Navigate to="/health/research" replace />} /></Routes></section>; }
