export type ProposalSectionId = 'executive-summary' | 'opportunities' | 'solution' | 'modules' | 'integrations' | 'security' | 'pilot' | 'kpis' | 'contact';

export const proposalSections: { id: ProposalSectionId; title: string; kicker: string; body: string; points: string[] }[] = [
  { id: 'executive-summary', title: 'Executive Summary', kicker: 'One connected operating layer', body: 'ATLAS proposes a governed orchestration layer that connects operational, financial, workforce, facilities, research and patient-experience workflows without requiring a health system to discard every existing platform.', points: ['One command layer across departments', 'Explicit source-state governance', 'Modular adoption rather than forced replacement'] },
  { id: 'opportunities', title: 'Problems & Opportunities', kicker: 'Reduce operational fragmentation', body: 'Fragmented workflows, duplicated dashboards and disconnected facility or workforce data create avoidable coordination cost. ATLAS targets those seams while keeping system-of-record boundaries visible.', points: ['Cross-department coordination', 'Operational visibility', 'Governed integration status'] },
  { id: 'solution', title: 'ATLAS Solution', kicker: 'Smart Health Ecosystem', body: 'The solution combines a command center, eighteen modular workspaces, shared identity, permissions, audit and integration contracts in a single ATLAS experience.', points: ['Proposal + Operations separation', 'Shared RBAC and audit', 'Reusable integration contracts'] },
  { id: 'modules', title: 'Module Portfolio', kicker: 'Eighteen connected workspaces', body: 'Enterprise operations, clinical operations, finance, workforce, pharmacy, supply chain, facilities, security, research and public-health awareness share one governed module graph.', points: ['18 routed modules', 'Shared navigation and data-state language', 'Cross-module handoffs'] },
  { id: 'integrations', title: 'Integrations', kicker: 'Connect without pretending', body: 'FHIR, HL7 v2, EHR, finance, workforce, pharmacy, facilities IoT, voice and public-health adapters remain contracts until authorized live connections pass health checks.', points: ['Configured is not Live', 'Authorization is explicit', 'Health-check evidence required'] },
  { id: 'security', title: 'Security & Governance', kicker: 'Least privilege by design', body: 'Tenant boundaries, RBAC, audit events and source-state governance protect every sensitive workflow. UI permissions never replace backend authorization.', points: ['Tenant + organization scope', 'Permission-aware actions', 'Auditable demo mutations'] },
  { id: 'pilot', title: 'Pilot Roadmap', kicker: 'Start where coordination is measurable', body: 'Recommended pilot: Command Center + Patient Experience + Smart Facilities + Health Intelligence, followed by measured expansion into revenue, workforce, pharmacy and supply chain.', points: ['Phase 1: visibility', 'Phase 2: operational workflows', 'Phase 3: authorized integrations'] },
  { id: 'kpis', title: 'KPI Framework', kicker: 'Measure before promising', body: 'Pilot KPIs should be baselined with authorized source data before targets are committed. Useful categories include queue time, work-order cycle time, integration availability and operational response time.', points: ['Baseline from authorized systems', 'No invented ROI figures', 'Compare before/after pilot windows'] },
  { id: 'contact', title: 'Request Pilot', kicker: 'Move from concept to validated pilot', body: 'This workspace is an ATLAS concept environment and does not represent an AdventHealth deployment or endorsement. A pilot would begin with technical discovery, data-source authorization and jointly defined success criteria.', points: ['Discovery', 'Security review', 'Pilot scope + success criteria'] }
];
